<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('categories')->insert([
            [
                'name' => 'Banner',
                'images' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEpOB50Gf-839DMNoHRlYYBAWP0TN73RHsGg&usqp=CAU',
                'type' => '1',
                'index' => '2',
                'status'=>'1',
                'action_name'=>null,
                'menu_top'=>'0',
                'key_name'=>'banner',
                'meta_keyword' => 'Banner' ,
                'meta_description' => '<p>Banner<br></p>',
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            [
                'name' => 'Dịch vụ',
                'images' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEpOB50Gf-839DMNoHRlYYBAWP0TN73RHsGg&usqp=CAU',
                'type' => '1',
                'index' => '3',
                'status'=>'1',
                'action_name'=>'home.service',
                'menu_top'=>'1',
                'key_name'=>'service',
                'meta_keyword' => 'Dịch vụ của chúng tôi' ,
                'meta_description' => '<h1>Ch&uacute;ng t&ocirc;i cung cấp đa dạng c&aacute;c dịch vụ về IT</h1>',
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            [
                'name' => 'Blog',
                'images' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEpOB50Gf-839DMNoHRlYYBAWP0TN73RHsGg&usqp=CAU',
                'type' => '1',
                'index' => '5',
                'status'=>'1',
                'action_name'=>'home.blog',
                'menu_top'=>'1',
                'key_name'=>'blog',
                'meta_keyword' => 'Blog' ,
                'meta_description' => '<h2>C&aacute;c Blog mới nhất</h2>',
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            [
                'name' => 'Giới thiệu',
                'images' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEpOB50Gf-839DMNoHRlYYBAWP0TN73RHsGg&usqp=CAU',
                'type' => '1',
                'index' => '1',
                'status'=>'1',
                'action_name'=>'home.about',
                'menu_top'=>'1',
                'key_name'=>'home.about',
                'meta_keyword' => 'Giới thiệu' ,
                'meta_description' => '<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Doloribus quam neque quibusdam corrupti aspernatur corporis alias nisi dolorum expedita veritatis voluptates minima.</p>',
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            [
                'name' => 'Sản phẩm',
                'images' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEpOB50Gf-839DMNoHRlYYBAWP0TN73RHsGg&usqp=CAU',
                'type' => '1',
                'index' => '2',
                'status'=>'1',
                'action_name'=>'home.product',
                'menu_top'=>'1',
                'key_name'=>'Sản phẩm  của chúng tôi',
                'meta_keyword' => 'Banner' ,
                'meta_description' => '<h2>Giới thiệu một số dự &aacute;n v&agrave; c&ocirc;ng việc</h2>',
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            [
                'name' => 'Khách hàng',
                'images' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEpOB50Gf-839DMNoHRlYYBAWP0TN73RHsGg&usqp=CAU',
                'type' => '1',
                'index' => '1',
                'status'=>'1',
                'action_name'=>null,
                'menu_top'=>'0',
                'key_name'=>'client',
                'meta_keyword' => 'Khách hàng' ,
                'meta_description' => '<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Doloribus quam neque quibusdam corrupti aspernatur corporis alias nisi dolorum expedita veritatis voluptates minima.</p>',
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            [
                'name' => 'Đội ngũ',
                'images' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEpOB50Gf-839DMNoHRlYYBAWP0TN73RHsGg&usqp=CAU',
                'type' => '1',
                'index' => '4',
                'status'=>'1',
                'action_name'=>'home.staff',
                'menu_top'=>'1',
                'key_name'=>'staff',
                'meta_keyword' => 'Đội ngũ' ,
                'meta_description' => '<h1>Đội ngũ ti&ecirc;n phong</h1>',
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            [
                'name' => 'Số liệu thống kê',
                'images' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEpOB50Gf-839DMNoHRlYYBAWP0TN73RHsGg&usqp=CAU',
                'type' => '1',
                'index' => '2',
                'status'=>'1',
                'action_name'=>null,
                'menu_top'=>'0',
                'key_name'=>'aboutService',
                'meta_keyword' => 'Giới thiệu dịch vụ' ,
                'meta_description' => '<p>Dịch vụ của ch&uacute;ng t&ocirc;i l&agrave; sự hỗ trợ cho c&ocirc;ng việc của bạn</p>',
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            [
                'name' => 'Thống kê',
                'images' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEpOB50Gf-839DMNoHRlYYBAWP0TN73RHsGg&usqp=CAU',
                'type' => '2',
                'index' => '2',
                'status'=>'1',
                'action_name'=>null,
                'menu_top'=>'0',
                'key_name'=>'achive',
                'meta_keyword' => 'Thống kê' ,
                'meta_description' => '<h2>Hoạt động của ch&uacute;ng t&ocirc;i</h2>',
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            [
                'name' => 'Thương hiệu',
                'images' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEpOB50Gf-839DMNoHRlYYBAWP0TN73RHsGg&usqp=CAU',
                'type' => '2',
                'index' => '2',
                'status'=>'1',
                'action_name'=>null,
                'menu_top'=>'0',
                'key_name'=>'brand',
                'meta_keyword' => 'Thương hiệu' ,
                'meta_description' => '<p>Thương hiệu</p>',
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            [
                'name' => 'Liên hệ',
                'images' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEpOB50Gf-839DMNoHRlYYBAWP0TN73RHsGg&usqp=CAU',
                'type' => '1',
                'index' => '6',
                'status'=>'1',
                'action_name'=>'home.contact',
                'menu_top'=>'1',
                'key_name'=>'contact',
                'meta_keyword' => 'Liên hệ' ,
                'meta_description' => '<h3><big>Để lại lời nhắn của bạn nếu muốn li&ecirc;n hệ với ch&uacute;ng t&ocirc;i</big></h3>',
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
        ]);
    }
}